// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTZhDmoJA41TOwTRwavwVdxk8D4NiXeBI',
    appId: '1:75861697380:web:d23f4622b157dcbed1d071',
    messagingSenderId: '75861697380',
    projectId: 'bookit-facf7',
    authDomain: 'bookit-facf7.firebaseapp.com',
    storageBucket: 'bookit-facf7.firebasestorage.app',
    measurementId: 'G-5RB3Q1TJP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdgQIrTuTWwLA-QXs9B_vj3kjRZhZe-SI',
    appId: '1:75861697380:android:51769824a8555037d1d071',
    messagingSenderId: '75861697380',
    projectId: 'bookit-facf7',
    storageBucket: 'bookit-facf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm-z_rIXevFkwchftewWNtcdi9Cszw2fc',
    appId: '1:75861697380:ios:6ac4b045bf0eec36d1d071',
    messagingSenderId: '75861697380',
    projectId: 'bookit-facf7',
    storageBucket: 'bookit-facf7.firebasestorage.app',
    iosBundleId: 'com.example.booking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm-z_rIXevFkwchftewWNtcdi9Cszw2fc',
    appId: '1:75861697380:ios:6ac4b045bf0eec36d1d071',
    messagingSenderId: '75861697380',
    projectId: 'bookit-facf7',
    storageBucket: 'bookit-facf7.firebasestorage.app',
    iosBundleId: 'com.example.booking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTZhDmoJA41TOwTRwavwVdxk8D4NiXeBI',
    appId: '1:75861697380:web:ff5b518adc4f5903d1d071',
    messagingSenderId: '75861697380',
    projectId: 'bookit-facf7',
    authDomain: 'bookit-facf7.firebaseapp.com',
    storageBucket: 'bookit-facf7.firebasestorage.app',
    measurementId: 'G-0HN8PM3YXS',
  );
}
